import { useEffect, useState } from 'react'
import type { KnowledgeSpace, Promotion, SearchHit } from '../../api/client'
import { PromotionDialog } from './PromotionDialog'

export function KnowledgeManager({ token, selectedVersionId }: { token: string; selectedVersionId?: string }) {
  const [query, setQuery] = useState(''); const [hits, setHits] = useState<SearchHit[]>([]); const [spaces, setSpaces] = useState<KnowledgeSpace[]>([]); const [promotions, setPromotions] = useState<Promotion[]>([]); const [dialog, setDialog] = useState(false)
  useEffect(() => { void Promise.all([fetch('/api/knowledge/spaces', { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.json()), fetch(`/api/knowledge/promotions${selectedVersionId ? `?version_id=${selectedVersionId}` : ''}`, { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.json())]).then(([spaceResult, promotionResult]) => { setSpaces(spaceResult.items); setPromotions(promotionResult.items) }) }, [selectedVersionId, token])
  async function search() { const response = await fetch('/api/knowledge/search', { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ query, mode: 'hybrid', limit: 10 }) }); if (response.ok) setHits(await response.json()) }
  return <main className="knowledge-workspace"><header><p className="eyebrow">Knowledge</p><h1>Search and governed promotion</h1></header><section className="feature-panel"><div className="search-row"><input aria-label="Knowledge search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search indexed sources" /><button type="button" disabled={!query.trim()} onClick={() => void search()}>Search</button></div><ul className="search-results">{hits.map((hit) => <li key={hit.chunk_id}><strong>{hit.title}</strong><span>{hit.heading_path.join(' / ')}</span><q>{hit.quote}</q></li>)}</ul></section><section className="feature-panel"><h2>Promotion requests</h2>{promotions.length === 0 ? <p className="muted">No promotion requests for this context.</p> : promotions.map((promotion) => <article className="promotion-row" key={promotion.id}><strong>{promotion.status}</strong><span>Version {promotion.version_id} → {promotion.target_space_id}</span></article>)}{selectedVersionId && <button type="button" onClick={() => setDialog(true)}>Request promotion</button>}</section>{dialog && <PromotionDialog token={token} versionId={selectedVersionId!} spaces={spaces} onClose={() => setDialog(false)} />}</main>
}
