import { useEffect, useState } from 'react'
import type { Contract, Requirement } from '../../api/client'

const blank = (documentType = '') => ({ domain: '', document_type: documentType, subject_organization: '', reporting_period: '', purpose: '', audience: '', requirements: [] as Requirement[], standard_ids: [] as string[], precedent_ids: [] as string[], reviewer_id: null as string | null })
export function WritingContractForm({ token, documentId, documentType, canConfirm }: { token: string; documentId: string; documentType: string; canConfirm: boolean }) {
  const [contract, setContract] = useState<Contract | null>(null); const [form, setForm] = useState(blank(documentType)); const [error, setError] = useState(''); const [saved, setSaved] = useState(false)
  useEffect(() => { void fetch(`/api/quality/documents/${documentId}/contract`, { headers: { Authorization: `Bearer ${token}` } }).then(async (response) => { if (response.status === 404) return; if (!response.ok) throw new Error(); const next = await response.json() as Contract; setContract(next); setForm(next.revision) }).catch(() => setError('Contract could not be loaded.')) }, [documentId, token])
  function update(field: keyof typeof form, value: string) { setForm((current) => ({ ...current, [field]: value })) }
  async function save() { setError(''); setSaved(false); const path = contract ? `/api/quality/contracts/${contract.id}/revisions` : `/api/quality/documents/${documentId}/contract`; const response = await fetch(path, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (!response.ok) { setError('Contract could not be saved.'); return } setContract(await response.json()); setSaved(true) }
  return <section className="feature-panel"><p className="eyebrow">Writing contract</p><h2>{contract ? `Revision ${contract.active_revision}` : 'Create contract'}</h2><div className="contract-fields">{(['domain', 'document_type', 'subject_organization', 'reporting_period', 'purpose', 'audience'] as const).map((field) => <label key={field}>{field.replaceAll('_', ' ')}<input value={String(form[field])} onChange={(event) => update(field, event.target.value)} /></label>)}</div><button type="button" onClick={() => void save()}>Save contract</button>{canConfirm && contract && <button type="button" onClick={async () => { const response = await fetch(`/api/quality/contracts/${contract.id}/confirm`, { method: 'POST', headers: { Authorization: `Bearer ${token}` } }); if (response.ok) setContract(await response.json()) }}>Confirm revision</button>}{saved && <p className="success">Saved.</p>}{error && <p className="error" role="alert">{error}</p>}</section>
}
