import { useState } from 'react'
import type { ReviewDetail } from '../../api/client'

export function ReviewPanel({ token, review, source, canReview, onRefresh }: { token: string; review: ReviewDetail | null; source: string; canReview: boolean; onRefresh: () => Promise<void> }) {
  const [draft, setDraft] = useState(''); const [error, setError] = useState(''); const [conflict, setConflict] = useState(false)
  const highlighted = review?.comments.filter((comment) => comment.version_id === review.version_id && comment.source_range.end <= source.length) ?? []
  async function comment() { if (!review || !draft.trim()) return; setError(''); try { const response = await fetch(`/api/reviews/${review.id}/comments`, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ source_range: { start: 0, end: Math.min(1, source.length) }, text: draft, expected_revision: review.workflow_revision }) }); if (response.status === 409) { setConflict(true); await onRefresh(); return } if (!response.ok) throw new Error(); setDraft(''); await onRefresh() } catch { setError('Comment could not be saved.') } }
  return <section className="feature-panel review-panel"><p className="eyebrow">Review</p><h2>{review ? review.state : 'No review selected'}</h2>{review && <p className="muted">Bound to version {review.version_id} · workflow revision {review.workflow_revision}</p>}{highlighted.map((comment) => <article key={comment.id} className="review-comment"><strong>{comment.status}</strong><p>{comment.text}</p><span>{comment.source_range.start}–{comment.source_range.end}</span></article>)}{canReview && review && <><textarea aria-label="Review comment" value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Add a comment for the selected source" /><button type="button" onClick={() => void comment()} disabled={!draft.trim()}>Add comment</button></>}{conflict && <p className="conflict" role="alert">The review changed. Your draft is retained; review the refreshed state before retrying.</p>}{error && <p className="error" role="alert">{error}</p>}</section>
}
